<?php 
$str='{
   "MaterialListPreviewScreen":[
      {
         "AnimalName":"Bear",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/bear.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/bear-2.png"
      },
      {
         "AnimalName":"Camel",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/camel.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/camel-2.png"
      },
      {
         "AnimalName":"Cat",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/cat.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/cat-2.png"
      },
      {
         "AnimalName":"Dinosour",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/dinosour.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/dinosour-2.png"
      },
      {
         "AnimalName":"Elephant",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/elephant.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/elephant-2.png"
      },
      {
         "AnimalName":"Horse",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/horse.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/horse-2.png"
      },
      {
         "AnimalName":"Iguana",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/iguana.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/iguana-2.png"
      },
      {
         "AnimalName":"Lion",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/lion.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/lion-2.png"
      },
      {
         "AnimalName":"Monkey",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/monkey.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/monkey-2.png"
      },
      {
         "AnimalName":"Mouse",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/mouse.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/mouse-2.png"
      },
      {
         "AnimalName":"Tiger",
         "MaterialPreviewImageURL":"http://animaldrawing.xyz/upload/tiger.png",
         "ArtBoardImgURL":"http://animaldrawing.xyz/upload/tiger-2.png"
      }
   ],
   "GIFScreen":[
      {
         "AnimalName":"Bear",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/13.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/14.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/15.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/16.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/17.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/18.png"
            }
         ]
      },
      {
         "AnimalName":"Camel",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Cat",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Dinosour",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Elephant",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Horse",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Iguana",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Lion",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Monkey",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Mouse",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      },
      {
         "AnimalName":"Tiger",
         "AnimalList":[
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_1.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_2.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_3.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_4.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_5.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_6.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_7.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_8.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_9.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_10.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_11.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_12.png"
            },
            {
               "GIF":"http://animaldrawing.xyz/upload/cat_13.png"
            }
         ]
      }
   ],
   "VideoPreviewScreen":[
      {
         "AnimalName":"Bear Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Bear_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Bear.mp4"
      },
      {
         "AnimalName":"Camel Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Camel_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Cat Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Cat_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Dinasaur Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Dinosour_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Elephant Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Elephant_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Horse Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Horse_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Iguana Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Iguana_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Lion Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Lion_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Monkey Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Monkey_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Mouse Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Mouse_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      },
      {
         "AnimalName":"Tiger Video",
         "PreviewImageURL":"http://animaldrawing.xyz/upload/Tiger_thumbnail.png",
         "YTB_VideoURL":"http://animaldrawing.xyz/upload/Camel.mp4"
      }
   ]
}';
$json = json_decode($str, true);  
echo json_encode($json);
?>
